server:
  port: 8080

jwt:
  secret: hwanSecretKey

#jwt:
#  header: Authorization
#  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw | base64
#  YWprbGdoc2Rma2xnanNkaGZnbGprc2RmZ2hsc2
#access-token-validity-in-seconds: 600 # 10 min

spring:
  security:
    user:
      name: admin
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: qna-board
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qnaboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 3642123@

  # ??? SQL ?? ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # hibernate ??
    database : mysql
    hibernate.ddl-auto : update
    hibernate.naming.strategy : org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true

  logging:
    level:
#      org.springframework.web.servlet: DEBUG
      org.springframework.security: debug
      root: info
      org.springframework.web: debug
    pateern:
      console: "[%d{HH:mm:ss.SSS}] [%-5level] [%logger{0}] - %msg%n"

# spring docs 설정
springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html




#  packages-to-scan: com.hwan.qnaboard
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    enabled: true                 # openAPI 인터페이스의 사용 여부를 설정.
#    path: demo-ui.html            # Swagger UI 경로 => localhost:8080/demo-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    displayRequestDuration: true  # Swagger-ui 에서 API 실행 시 처리 소요 시간의 표시 여부를 설정한다.
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true


