DROP TABLE IF EXISTS board;
CREATE TABLE board (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       content TEXT,
                       writer VARCHAR(50) NOT NULL,
                       createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
                       modifiedDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO board (title, content, writer, createdDate, modifiedDate)
VALUES ('스프링부트', '첫 번째 게시글의 내용입니다.', 'hwan', now(), now()),
       ('mvc 패턴', '두 번째 게시글의 내용입니다.', 'rok', now(), now()),
       ('부트스트랩', '세 번째 게시글의 내용입니다.', 'lyn', now(), now()),
        ('페이징', '네 번째 게시글의 내용입니다.', 'yae', now(), now()),
        ('레이아웃', '다섯 번째 게시글의 내용입니다.', 'a', now(), now()),
        ('타임리프', '여섯 번째 게시글의 내용입니다.', 'rym', now(), now()),
        ('데이터 베이스', '일곱 번째 게시글의 내용입니다.', 'ji', now(), now()),
        ('Rest Api', '여덟 번째 게시글의 내용입니다.', 'yoo', now(), now()),
        ('JPA', '아홉 번째 게시글의 내용입니다.', 'sieun', now(), now()),
        ('Hello World', '열 번째 게시글의 내용입니다.', 'jungsik', now(), now()),
        ('푸터', '열 한 번째 게시글의 내용입니다.', 'jungmin', now(), now()),
        ('헤더', '열 두 번째 게시글의 내용입니다.', 'youngtak', now(), now()),
        ('지유', '열 세 번째 게시글의 내용입니다.', 'sangil', now(), now()),
        ('혼자밥먹는다', '열 네 번째 게시글의 내용입니다.', 'minjune', now(), now()),
        ('잠투정', '열 다섯 번째 게시글의 내용입니다.', 'mock', now(), now()),
        ('으엥', '열 여섯 번째 게시글의 내용입니다.', 'jungok', now(), now()),
        ('으엥2', '열 일곱 번째 게시글의 내용입니다.', 'namkung', now(), now()),
        ('잠', '열 여덟 번째 게시글의 내용입니다.', 'jaeEung', now(), now()),
        ('페이징테스트', '스무 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 한 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 두 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 세 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 네 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 다섯 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 여섯 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 일곱 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 여덟 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '스물 아홉 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
       ('페이징테스트', '서른 번째 게시글의 내용입니다.', 'jaechun', now(), now()),
        ('아이', '서른 한 번째 게시글의 내용입니다.', 'cka', now(), now());

